/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;



import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author timgl
 */
public class UpdateUIAdmin extends javax.swing.JFrame {

    AdminUI adminUI;
    InsurancePolicy policy;
    /**
     * Creates new form UpdateUI
     * @param policy
     * @param adminUI
     */
    public UpdateUIAdmin(InsurancePolicy policy, AdminUI adminUI) {
        
        this.policy = policy;
        this.adminUI = adminUI;
        initComponents();
         
        
        // populate form with existing policy details
        policyHolderText.setText(policy.getPolicyHolderName());
        policyIdText.setText(policy.getId()+"");
        claimsText.setText(policy.getNumberOfClaims()+"");
        typeComboBox.setModel(new DefaultComboBoxModel<>(carType.values()));
        typeComboBox.setSelectedItem(this.policy.getCar().getType());
        modelText.setText(policy.getCar().getModel());
        buildYearText.setText(policy.getCar().getManufacturingYear()+"");
        priceText.setText(String.format("%.2f",policy.getCar().getPrice()));
        expYearText.setText(policy.getExpiryDate().getYear()+"");
        expMonthText.setText(policy.getExpiryDate().getMonth()+"");
        expDayText.setText(policy.getExpiryDate().getDay()+"");
        
        policyIdText.setEnabled(false);
        
        // check policy type and populate appropriate fields
        if (policy instanceof ThirdPartyPolicy)
        {
            thirdPartyRadio.setSelected(true);
            comprehensiveRadio.setSelected(false);
            levelLabel.setVisible(false);
            levelText.setVisible(false);
            commentAgeLabel.setText("Comments");
            commentAgeText.setText(((ThirdPartyPolicy) policy).getComment());
        }
        else
        {
            thirdPartyRadio.setSelected(false);
            comprehensiveRadio.setSelected(true);
            commentAgeLabel.setText("Driver Age");
            levelLabel.setVisible(true);
            levelText.setVisible(true);
            commentAgeText.setText(((ComprehensivePolicy)policy).getDriverAge()+"");
            levelText.setText(((ComprehensivePolicy)policy).getLevel()+"");
        }
        
        thirdPartyRadio.setEnabled(false);
        comprehensiveRadio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPolicy = new javax.swing.JPanel();
        thirdPartyRadio = new javax.swing.JRadioButton();
        comprehensiveRadio = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        policyHolderText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        policyIdText = new javax.swing.JTextField();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        modelText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buildYearText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        expYearText = new javax.swing.JTextField();
        expMonthText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        expDayText = new javax.swing.JTextField();
        commentAgeLabel = new javax.swing.JLabel();
        commentAgeText = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        levelText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        updateBut = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        claimsText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        thirdPartyRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thirdPartyRadio.setText("Third Party Policy");
        thirdPartyRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thirdPartyRadioStateChanged(evt);
            }
        });
        thirdPartyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdPartyRadioActionPerformed(evt);
            }
        });

        comprehensiveRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comprehensiveRadio.setText("Comprehensive Policy");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Policy Holder Name");

        policyHolderText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Policy ID ");
        jLabel11.setToolTipText("");

        policyIdText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        typeComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeComboBox.setToolTipText("Tim Glasgow 7409072");
        typeComboBox.setName(""); // NOI18N
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Car Type");

        modelText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Model");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("ManuYear");

        buildYearText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Price");

        priceText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Year");
        jLabel18.setToolTipText("");

        expYearText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        expMonthText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Month");
        jLabel19.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Day");
        jLabel20.setToolTipText("");

        expDayText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        commentAgeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        commentAgeLabel.setText("Comment");
        commentAgeLabel.setToolTipText("");

        commentAgeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        levelLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        levelLabel.setText("Level");
        levelLabel.setToolTipText("");

        levelText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        updateBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBut.setForeground(new java.awt.Color(255, 51, 51));
        updateBut.setText("UPDATE");
        updateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Number of Claims");
        jLabel12.setToolTipText("");

        claimsText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        claimsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimsTextActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPolicyLayout = new javax.swing.GroupLayout(AddPolicy);
        AddPolicy.setLayout(AddPolicyLayout);
        AddPolicyLayout.setHorizontalGroup(
            AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPolicyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32))
                    .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddPolicyLayout.createSequentialGroup()
                            .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AddPolicyLayout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AddPolicyLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel16))))))
                            .addGap(12, 12, 12))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPolicyLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19)
                                .addComponent(commentAgeLabel)
                                .addComponent(levelLabel))
                            .addGap(32, 32, 32))))
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(expDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(policyHolderText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddPolicyLayout.createSequentialGroup()
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(claimsText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(policyIdText, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(AddPolicyLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125)
                        .addComponent(updateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buildYearText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(priceText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(expMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPolicyLayout.createSequentialGroup()
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(modelText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 124, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thirdPartyRadio)
                            .addComponent(comprehensiveRadio))
                        .addGap(35, 35, 35)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        AddPolicyLayout.setVerticalGroup(
            AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPolicyLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policyHolderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(policyIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(claimsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(modelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buildYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(AddPolicyLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(thirdPartyRadio)
                        .addGap(18, 18, 18)
                        .addComponent(comprehensiveRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(21, 21, 21)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(expYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(expMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentAgeLabel))
                .addGap(21, 21, 21)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBut)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void claimsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claimsTextActionPerformed

    private void updateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButActionPerformed

        try
        {
            String holder = policyHolderText.getText();
            //            int id = Integer.parseInt(policyIdText.getText());
            carType type = (carType) typeComboBox.getSelectedItem();
            String model = modelText.getText();
            int carYear = Integer.parseInt(buildYearText.getText());
            double price = Double.parseDouble(priceText.getText());
            int claimsNo = Integer.parseInt(claimsText.getText());
            int year = Integer.parseInt(expYearText.getText());
            int month = Integer.parseInt(expMonthText.getText());
            int day = Integer.parseInt(expDayText.getText());
            MyDate date = new MyDate(year, month, day);
            Car car = new Car( model, type, carYear, price);
            policy.setPolicyHolderName(holder);
            policy.setCar(car);
            policy.setNumberOfClaims(claimsNo);
            policy.setExpiryDate(date);

            if (thirdPartyRadio.isSelected())
            {
                String comments = commentAgeText.getText();
                ((ThirdPartyPolicy)policy).setComment(comments);
            }
            else
            {
                int age = Integer.parseInt(commentAgeText.getText());
                ((ComprehensivePolicy)policy).setDriverAge(age);
                int level = Integer.parseInt(levelText.getText());
                ((ComprehensivePolicy)policy).setLevel(level);
            }
            JOptionPane.showMessageDialog(this, "Policy has been updated successfully.");
            adminUI.fillTable();
            this.dispose();
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Invalid Input! Please check fields that require numeric inputs.");
        }
    }//GEN-LAST:event_updateButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        clearPolicyForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void thirdPartyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdPartyRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdPartyRadioActionPerformed

    private void thirdPartyRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thirdPartyRadioStateChanged

    }//GEN-LAST:event_thirdPartyRadioStateChanged

    private void clearPolicyForm() // method to clear entered policy details from Add Policy form
    {
        policyHolderText.setText("");
        policyIdText.setText("");
        modelText.setText("");
        buildYearText.setText("");
        priceText.setText("");
        claimsText.setText("");
        expYearText.setText("");
        expMonthText.setText("");
        expDayText.setText("");
        commentAgeText.setText("");
        levelText.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPolicy;
    private javax.swing.JTextField buildYearText;
    private javax.swing.JTextField claimsText;
    private javax.swing.JLabel commentAgeLabel;
    private javax.swing.JTextField commentAgeText;
    private javax.swing.JRadioButton comprehensiveRadio;
    private javax.swing.JTextField expDayText;
    private javax.swing.JTextField expMonthText;
    private javax.swing.JTextField expYearText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField levelText;
    private javax.swing.JTextField modelText;
    private javax.swing.JTextField policyHolderText;
    private javax.swing.JTextField policyIdText;
    private javax.swing.JTextField priceText;
    private javax.swing.JRadioButton thirdPartyRadio;
    private javax.swing.JComboBox<carType> typeComboBox;
    private javax.swing.JButton updateBut;
    // End of variables declaration//GEN-END:variables
}
